### ISSUE TITLE
Cannot build with GHC 8.8

### ISSUE THREAD

**Issue by ocharles** [luqui/control-monad-omega#4]
```
Building library for control-monad-omega-0.3.1..
[1 of 1] Compiling Control.Monad.Omega ( Control/Monad/Omega.hs, dist/build/Control/Monad/Omega.o )

Control/Monad/Omega.hs:75:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
75 |     fail _ = Omega []
   |     ^^^^
```

**Comment by ocharles** [comment]
This was fixed in https://github.com/luqui/control-monad-omega/commit/76c71e8917eec275ba423959f00a34583b5c7215 - just needs to be released to Hackage.

**Comment by luqui** [comment]
Was it not released?  I thought i did

**Comment by ocharles** [comment]
Huh, it was... let me try building from Hackage again

**Comment by ocharles** [comment]
Yes, apologies - all is well! I see in my error report above I was building 0.3.1.
